[project]
name = "comicbook-guy"
version = "0.1.0"
description = "A helper tool to organise and monitor comic book directories"
authors = [
    {name = "Tom Freeman", email = "tomrfreeman3@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "numpy (>=2.5.2,<3.0.0)",
    "rapidfuzz (>=3.14.6,<4.0.0)",
    "comicbox (>=4.8.7,<5.0.0)"
]

[tool.poetry]
packages = [
    { include = "comicbookguy" }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
